---
eyeHeight: 1.09                   # m height eye level
radius: 0.1                       # 10cm radius cylinder
radialClearance: 0.2              # clearance to leave from center of agent for shortest path computations
mass: 32.0                        # kg weight
coeffRestitution: 0.0             # ratio of relative velocity before and after collision in direction of collision normal
stepAcceleration: 20.0            # m/s^2
maxSpeed: 2.0                     # m/s
linearFriction: 0.5               # coefficient of friction applied every step (k in F=-k*m*v/dt)
turnAcceleration: 12.5663706144   # rad/s^2
maxAngularSpeed: 12.5663706144    # rad/s
angularFriction: 1.0              # coefficient of angular friction applied every step (k in tau=-k*m*w/dt)
